@startuml diagram
title Dynamic CRUD Operation Endpoint

package "Endpoint" {
  [Create] --> (POST /api)
  [Read] --> (GET /api/user:_id)
  [Update] --> (PUT /api/user:_id)
  [Delete] --> (DELETE /api/user:_id)
}

database "Database" {
  [users]
}
+----------------+         +----------------+         +------------------+         +----------------+          +-----------------+
|   UserEndpoint |         |  UserController|         |    UserService  |         | UserRepository |         |       User      |
+----------------+         +----------------+         +------------------+         +----------------+          +-----------------+
| +createUser()  |         | +createUser()  |         | +createUser()   |         | +save()        |          | - id: string     |
| +updateUser()  |   ----> | +updateUser()  |  -----> | +updateUser()   | ----->  | +findById()   |  -----    | - name: string   |
| +readUserById()|         | +readUserById()|         | +readUserById() |         |+findByIdAnd()  |          |                  |
| +deleteUserById|         | +deleteUserById|         | +deleteUserById |         |+findByIdAndDelete()|      |                  |
+----------------+         +----------------+         +------------------+         +----------------+          +-----------------+


@enduml
